const JOB_CONFIG = Object.freeze({
  DEFAULT_ATTEMPTS: 3,

  DEFAULT_BACKOFF_MS: 5000,

  DEFAULT_REMOVE_ON_COMPLETE: 100,

  DEFAULT_REMOVE_ON_FAIL: 100,

  DEFAULT_CONCURRENCY: 5,

  MAX_ATTEMPTS: 10,
});

module.exports = {
  JOB_CONFIG,
};