// =====================================================
// Security Event Types
// =====================================================

const SECURITY_EVENTS = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGOUT: "LOGOUT",
  LOGOUT_ALL_DEVICES: "LOGOUT_ALL_DEVICES",

  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REVOKED: "SESSION_REVOKED",

  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  TOKEN_REFRESH_FAILED: "TOKEN_REFRESH_FAILED",

  TOKEN_REUSE_DETECTED:
    "TOKEN_REUSE_DETECTED",

  TOKEN_FAMILY_REVOKED:
    "TOKEN_FAMILY_REVOKED",

  PASSWORD_CHANGED:
    "PASSWORD_CHANGED",

  PASSWORD_RESET_REQUESTED:
    "PASSWORD_RESET_REQUESTED",

  PASSWORD_RESET_COMPLETED:
    "PASSWORD_RESET_COMPLETED",

  ACCOUNT_LOCKED:
    "ACCOUNT_LOCKED",

  ACCOUNT_UNLOCKED:
    "ACCOUNT_UNLOCKED",

  SUSPICIOUS_ACTIVITY:
    "SUSPICIOUS_ACTIVITY",
});

module.exports = {
  SECURITY_EVENTS,
};